//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Langauge
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Lang_Level { get; set; }
        public Nullable<System.Guid> FK_Member { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
