//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member_Group
    {
        public int ID { get; set; }
        public Nullable<System.Guid> FK_Member { get; set; }
        public Nullable<int> FK_Group { get; set; }
        public Nullable<System.DateTime> Date_Join { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Member Member { get; set; }
    }
}
