//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upload_Media
    {
        public int ID { get; set; }
        public Nullable<int> FK_Member_Section { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
    
        public virtual Education Education { get; set; }
        public virtual Work_Experience Work_Experience { get; set; }
    }
}
