//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work_Experience
    {
        public Work_Experience()
        {
            this.Links = new HashSet<Link>();
            this.Upload_Media = new HashSet<Upload_Media>();
        }
    
        public int ID { get; set; }
        public string Jop_Title { get; set; }
        public Nullable<int> FK_Org { get; set; }
        public string Location { get; set; }
        public Nullable<int> From_Year { get; set; }
        public Nullable<int> From_Month { get; set; }
        public Nullable<int> To_Year { get; set; }
        public Nullable<int> To_Month { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> FK_Member { get; set; }
    
        public virtual ICollection<Link> Links { get; set; }
        public virtual Member Member { get; set; }
        public virtual ICollection<Upload_Media> Upload_Media { get; set; }
    }
}
